In [30]:
!py -m pip install numpy


In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,4],[7,13,21]])
print(arr.shape)

(2, 3)


In [31]:
n=5
m=7
arrayy=np.ones((n, m)) * 7
arrayy

array([[7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7.]])

In [6]:
RANDOM_ARR = np.random.rand(4, 3, 4)

print(RANDOM_ARR)


n = 3
EYE = np.eye(n)

print(EYE)

[[[0.0503798  0.51424688 0.29187722 0.46272579]
  [0.57601705 0.80487471 0.54791898 0.70073422]
  [0.87252128 0.56216692 0.19216299 0.05428475]]

 [[0.06301887 0.95522063 0.27882173 0.62305999]
  [0.35801175 0.51558738 0.84963108 0.31223802]
  [0.63269505 0.7343038  0.98032596 0.70894782]]

 [[0.61136219 0.73775334 0.73234905 0.40603081]
  [0.89435247 0.40761523 0.39920045 0.79983989]
  [0.1198621  0.73626433 0.70955297 0.91396498]]

 [[0.73054712 0.96987841 0.24253021 0.23939483]
  [0.45591565 0.13337077 0.84808055 0.34135821]
  [0.0921061  0.84135345 0.72336107 0.52212607]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
y = np.array([[1,2,3],[4,5,6]])
y_transpose=y.reshape(3,2)
print(y_transpose)
y_flattened=y.reshape(6,)
print(y_flattened)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [27]:
arr = np.random.randint(1,10,size=(4,5,7,3))

# Let's say I want to change this matrix to a column vector. 
# It's pretty obvious that the new numpy array must have 2 dimensions and one of them is 1 (Since it's a column vector).
# This means I can skip the number of elements in other dimension (Numpy can calculate this on its own) and instead write -1 for ease

arr_new = arr.reshape(1,-1)
print(arr_new.shape)

(1, 420)


In [29]:
# What's the easiest way to create an array with shape (3,4) that is the same as
# the same array in the statement below?
# np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# numpy.ndarray is a homogeneous array, which means every array has a
# particular data type. What datatype does "arr" have?
print(arr.dtype)


int64


In [32]:
# Another very useful function is numpy.linspace that generates an array of equally spaced numbers over any given interval.

start = 0.1
end =   0.9
arrr=np.linspace(start,end,num=10,endpoint=True,axis=0)

In [33]:
# Akin to a regular list, we can slice numpy arrays as well, in various ways
# Note that indexing starts at 0 (similar to C), and that the last index is not included

arr1 = np.array([1,2,3,4,5])

print(arr1)
print(arr1[0:5])
print(arr1[0:4])
print(arr1[0:4:1])
print(arr1[0:4:2])
print(arr1[::-1])

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4]
[1 2 3 4]
[1 3]
[5 4 3 2 1]


In [34]:
# Unlike normal Python lists, you could slice multi-dimensional arrays too.
arr = np.arange(40).reshape(4,-1)
print(arr)
print(arr[1:4,2:5])

# Try changing the above values to get a better understanding of slicing in numpy arrays 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[12 13 14]
 [22 23 24]
 [32 33 34]]


In [36]:
# Try running this piece of code. Is the output the same as the one you expected?

arr = np.random.randint(10,size=6) # Shape can be an integer (for a 1D array) or a tuple (for Multi-Dimensional Arrays)
print(arr)

new_arr = arr

arr[0] = 100
print(arr)
print(new_arr)

[6 4 4 4 8 1]
[100   4   4   4   8   1]
[100   4   4   4   8   1]


In [ ]:
# When you assign an array to a new variable in Python (using =), it does not create a copy of the original array. 
# Instead, it creates a reference to the same memory location. 
# This means that any changes made to the new variable (new_arr in this case) will also affect the original variable (arr), as they both point to the same data.


# The interesting question now is how do you create a copy of an array which is completely independent of the original array.
# Luckily, numpy provides a function called copy() which does exactly that.

arr = np.random.randint(10,size=6)
print(arr)

new_arr = arr.copy()
arr[0] = -39
print(arr)
print(new_arr)

In [42]:
arr=np.random.rand(3,2)
print(arr)

[[0.9083738  0.06863852]
 [0.07533272 0.54353469]
 [0.08939972 0.38239327]]


In [43]:
# The reason you see different outputs every time is because the random numbers are generated using a seed. 
# The seed is the starting point for the random number generator algorithm and its value determines the sequence of random numbers generated.
# By default, the seed is set to None, which means that the random number generator uses the current system time as the seed.

# But you can bypass this behaviour. You can set the seed to a specific value using the np.random.seed() function

np.random.seed(31) # The seed can be set to any integer between 0 and 2**32 - 1


arr=np.random.rand(3,2)
print(arr)



[[0.28605382 0.95810557]
 [0.77031293 0.98687   ]
 [0.20816546 0.13691705]]


In [47]:
arr=np.random.randint(5,12, size=(2,4))
print(arr)

[[ 9  8 11  8]
 [ 8  7  5  5]]


In [49]:
arr = np.arange(10).reshape(2,5)
print(arr)
print(arr.sum())

[[0 1 2 3 4]
 [5 6 7 8 9]]
45


In [50]:
arr = np.arange(10).reshape(2,5)
print(arr)
print(arr.mean())
print(arr.std())
print(arr.min())


[[0 1 2 3 4]
 [5 6 7 8 9]]
4.5
2.8722813232690143
0


In [58]:
arr = np.array([[1,2,9],
                [3,4,5],
                [-3,8,7]])
print(arr,"\n\n")

print(arr.max(axis=0),"\n\n")

print(arr.max(axis=1),"\n\n")

# In the case of multi-dimensional arrays, the above functions can take an additional parameter 'axis'
# to define the dimension along which the operation is to be performed.

# You can also run the above functions without the axis parameter to get the result for the entire array as if it were a 1D array.

print(arr.max(),arr.min(),arr.mean())

[[ 1  2  9]
 [ 3  4  5]
 [-3  8  7]] 


[3 8 9] 


[9 5 8] 


9 -3 4.0


In [59]:
# Let's see what happens when we multiply an array with
# 1) a scalar
# 2) an array of same shape

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1,"\n-----")

print(arr1*2,"\n-----")  # Scalar multiplication
print(arr1*arr2)           # Element-wise multiplication


# Observe the outputs of the code above.
# Now think of a way to create arr_square which is the square of each element of arr.

arr = np.random.randint(12,size=3)

print(arr)



arr_square = arr**2

print(arr_square)

[1 2 3] 
-----
[2 4 6] 
-----
[ 4 10 18]
[ 1 10 11]
[  1 100 121]


In [60]:
# Just like the multiplication operator, you can use the addition, subtraction, division, and exponentiation operators with constants on numpy arrays as well.

arr = np.arange(12).reshape(3,4)

print(arr)
print(arr+1)
print(arr-1)
print(arr*2)
print(arr/2)
print(arr//2)
print(arr**3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]


In [64]:
arr1 = np.array([1,2,3,4])
print(arr*arr1,'\n')
print(arr,'\n')

arr2 = np.array([7,2,5,8])
print(arr2*arr,'\n')

[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  2 10 24]
 [28 10 30 56]
 [56 18 50 88]] 



In [65]:
# Try to figure out what happens in the following example
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(4)
print(arr1,"\n")
print(arr2,"\n")

print(arr1+arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[0 1 2 3] 

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [70]:
# Can you explain why the following code throws an error?
arr3 = np.arange(12).reshape(3,4)
arr4 = np.arange(3)
print(arr3,"\n")
print(arr4,"\n")

print(arr3+arr4)

#arr3 has 4 columns while arr4 has only 3 columns, making it not possinle to add them as the columns must be the same.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[0 1 2] 



ValueError: operands could not be broadcast together with shapes (3,4) (3,) 